// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	AuthnRequest
	Attribute
	User
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthnRequest struct {
	ID                             string                     `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Version                        string                     `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
	IssueInstant                   *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=IssueInstant" json:"IssueInstant,omitempty"`
	Issuer                         string                     `protobuf:"bytes,4,opt,name=Issuer" json:"Issuer,omitempty"`
	Destination                    string                     `protobuf:"bytes,5,opt,name=Destination" json:"Destination,omitempty"`
	AssertionConsumerServiceURL    string                     `protobuf:"bytes,6,opt,name=AssertionConsumerServiceURL" json:"AssertionConsumerServiceURL,omitempty"`
	ProtocolBinding                string                     `protobuf:"bytes,7,opt,name=ProtocolBinding" json:"ProtocolBinding,omitempty"`
	AttributeConsumingServiceIndex string                     `protobuf:"bytes,8,opt,name=AttributeConsumingServiceIndex" json:"AttributeConsumingServiceIndex,omitempty"`
	RelayState                     string                     `protobuf:"bytes,9,opt,name=RelayState" json:"RelayState,omitempty"`
}

func (m *AuthnRequest) Reset()                    { *m = AuthnRequest{} }
func (m *AuthnRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthnRequest) ProtoMessage()               {}
func (*AuthnRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthnRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuthnRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AuthnRequest) GetIssueInstant() *google_protobuf.Timestamp {
	if m != nil {
		return m.IssueInstant
	}
	return nil
}

func (m *AuthnRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *AuthnRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *AuthnRequest) GetAssertionConsumerServiceURL() string {
	if m != nil {
		return m.AssertionConsumerServiceURL
	}
	return ""
}

func (m *AuthnRequest) GetProtocolBinding() string {
	if m != nil {
		return m.ProtocolBinding
	}
	return ""
}

func (m *AuthnRequest) GetAttributeConsumingServiceIndex() string {
	if m != nil {
		return m.AttributeConsumingServiceIndex
	}
	return ""
}

func (m *AuthnRequest) GetRelayState() string {
	if m != nil {
		return m.RelayState
	}
	return ""
}

type Attribute struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type User struct {
	Name      string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Attribute []*Attribute `protobuf:"bytes,4,rep,name=attribute" json:"attribute,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAttribute() []*Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthnRequest)(nil), "model.AuthnRequest")
	proto.RegisterType((*Attribute)(nil), "model.Attribute")
	proto.RegisterType((*User)(nil), "model.User")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0xe3, 0x40,
	0x18, 0xc7, 0x69, 0x92, 0xb6, 0x9b, 0x27, 0x65, 0x77, 0x19, 0x96, 0x65, 0xa8, 0x50, 0x43, 0x4f,
	0x39, 0xa5, 0x50, 0xf1, 0x2a, 0x56, 0x8b, 0x10, 0xf1, 0x20, 0xa9, 0xf5, 0x3e, 0x6d, 0x1f, 0xe3,
	0x40, 0x32, 0x53, 0xe7, 0xa5, 0xe8, 0x17, 0xf0, 0x73, 0x4b, 0x27, 0x4d, 0xad, 0x22, 0x7a, 0xcb,
	0xef, 0x9f, 0xff, 0x4b, 0xe0, 0x09, 0x44, 0x95, 0x5c, 0x61, 0x99, 0xae, 0x95, 0x34, 0x92, 0xb4,
	0x1d, 0xf4, 0x8f, 0x0b, 0x29, 0x8b, 0x12, 0x47, 0x4e, 0x5c, 0xd8, 0x87, 0x91, 0xe1, 0x15, 0x6a,
	0xc3, 0xaa, 0x75, 0xed, 0x1b, 0xbe, 0xfa, 0xd0, 0x9b, 0x58, 0xf3, 0x28, 0x72, 0x7c, 0xb2, 0xa8,
	0x0d, 0xf9, 0x0d, 0x5e, 0x36, 0xa5, 0xad, 0xb8, 0x95, 0x84, 0xb9, 0x97, 0x4d, 0x09, 0x85, 0xee,
	0x3d, 0x2a, 0xcd, 0xa5, 0xa0, 0x9e, 0x13, 0x1b, 0x24, 0x67, 0xd0, 0xcb, 0xb4, 0xb6, 0x98, 0x09,
	0x6d, 0x98, 0x30, 0xd4, 0x8f, 0x5b, 0x49, 0x34, 0xee, 0xa7, 0xf5, 0x64, 0xda, 0x4c, 0xa6, 0x77,
	0xcd, 0x64, 0xfe, 0xc1, 0x4f, 0xfe, 0x43, 0xc7, 0xb1, 0xa2, 0x81, 0x2b, 0xde, 0x11, 0x89, 0x21,
	0x9a, 0xa2, 0x36, 0x5c, 0x30, 0xb3, 0x5d, 0x6d, 0xbb, 0x97, 0x87, 0x12, 0x39, 0x87, 0xa3, 0x89,
	0xd6, 0xa8, 0xb6, 0x70, 0x29, 0x85, 0xb6, 0x15, 0xaa, 0x19, 0xaa, 0x0d, 0x5f, 0xe2, 0x3c, 0xbf,
	0xa1, 0x1d, 0x97, 0xf8, 0xce, 0x42, 0x12, 0xf8, 0x73, 0xbb, 0xfd, 0xbe, 0xa5, 0x2c, 0x2f, 0xb8,
	0x58, 0x71, 0x51, 0xd0, 0xae, 0x4b, 0x7d, 0x96, 0xc9, 0x15, 0x0c, 0x26, 0xc6, 0x28, 0xbe, 0xb0,
	0x06, 0xeb, 0x22, 0x2e, 0x8a, 0x5d, 0x53, 0x26, 0x56, 0xf8, 0x4c, 0x7f, 0xb9, 0xe0, 0x0f, 0x2e,
	0x32, 0x00, 0xc8, 0xb1, 0x64, 0x2f, 0x33, 0xc3, 0x0c, 0xd2, 0xd0, 0x65, 0x0e, 0x94, 0xe1, 0x29,
	0x84, 0xfb, 0x06, 0x42, 0x20, 0x10, 0xac, 0xc2, 0xdd, 0x19, 0xdc, 0x33, 0xf9, 0x07, 0xed, 0x0d,
	0x2b, 0x2d, 0x52, 0x2f, 0xf6, 0x93, 0x30, 0xaf, 0x61, 0x78, 0x0d, 0xc1, 0x5c, 0xa3, 0xfa, 0x32,
	0x91, 0x42, 0xc8, 0x9a, 0x4a, 0x1a, 0xc4, 0x7e, 0x12, 0x8d, 0xff, 0xa6, 0xf5, 0x4f, 0xb2, 0x9f,
	0xca, 0xdf, 0x2d, 0x8b, 0x8e, 0x3b, 0xd9, 0xc9, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0xc9,
	0x4a, 0x48, 0x49, 0x02, 0x00, 0x00,
}
