// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	AuthnRequest
	User
	Attribute
	ArtifactResponse
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Allows storage of the request for cases where there
// is a user wait state such as entering a password
type AuthnRequest struct {
	ID                             string                     `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Version                        string                     `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
	IssueInstant                   *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=IssueInstant" json:"IssueInstant,omitempty"`
	Issuer                         string                     `protobuf:"bytes,4,opt,name=Issuer" json:"Issuer,omitempty"`
	Destination                    string                     `protobuf:"bytes,5,opt,name=Destination" json:"Destination,omitempty"`
	AssertionConsumerServiceURL    string                     `protobuf:"bytes,6,opt,name=AssertionConsumerServiceURL" json:"AssertionConsumerServiceURL,omitempty"`
	ProtocolBinding                string                     `protobuf:"bytes,7,opt,name=ProtocolBinding" json:"ProtocolBinding,omitempty"`
	AttributeConsumingServiceIndex string                     `protobuf:"bytes,8,opt,name=AttributeConsumingServiceIndex" json:"AttributeConsumingServiceIndex,omitempty"`
	RelayState                     string                     `protobuf:"bytes,9,opt,name=RelayState" json:"RelayState,omitempty"`
}

func (m *AuthnRequest) Reset()                    { *m = AuthnRequest{} }
func (m *AuthnRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthnRequest) ProtoMessage()               {}
func (*AuthnRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthnRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuthnRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AuthnRequest) GetIssueInstant() *google_protobuf.Timestamp {
	if m != nil {
		return m.IssueInstant
	}
	return nil
}

func (m *AuthnRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *AuthnRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *AuthnRequest) GetAssertionConsumerServiceURL() string {
	if m != nil {
		return m.AssertionConsumerServiceURL
	}
	return ""
}

func (m *AuthnRequest) GetProtocolBinding() string {
	if m != nil {
		return m.ProtocolBinding
	}
	return ""
}

func (m *AuthnRequest) GetAttributeConsumingServiceIndex() string {
	if m != nil {
		return m.AttributeConsumingServiceIndex
	}
	return ""
}

func (m *AuthnRequest) GetRelayState() string {
	if m != nil {
		return m.RelayState
	}
	return ""
}

// Allows storage of user information to avoid
// repeated logins, basis of SSO
type User struct {
	Name       string       `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Format     string       `protobuf:"bytes,2,opt,name=Format" json:"Format,omitempty"`
	Context    string       `protobuf:"bytes,3,opt,name=Context" json:"Context,omitempty"`
	IP         string       `protobuf:"bytes,4,opt,name=IP" json:"IP,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,5,rep,name=Attributes" json:"Attributes,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *User) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *User) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *User) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// User attributes
type Attribute struct {
	Name  string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value []string `protobuf:"bytes,2,rep,name=Value" json:"Value,omitempty"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// Allows storage of data required for artifact
// response until service provider retrieves it
type ArtifactResponse struct {
	User    *User         `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Request *AuthnRequest `protobuf:"bytes,2,opt,name=Request" json:"Request,omitempty"`
}

func (m *ArtifactResponse) Reset()                    { *m = ArtifactResponse{} }
func (m *ArtifactResponse) String() string            { return proto.CompactTextString(m) }
func (*ArtifactResponse) ProtoMessage()               {}
func (*ArtifactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ArtifactResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ArtifactResponse) GetRequest() *AuthnRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthnRequest)(nil), "model.AuthnRequest")
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*Attribute)(nil), "model.Attribute")
	proto.RegisterType((*ArtifactResponse)(nil), "model.ArtifactResponse")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x25, 0x9b, 0x2f, 0xf7, 0x6e, 0xd1, 0x32, 0x8a, 0x0c, 0x15, 0xda, 0x25, 0x4f, 0xfb, 0xe2,
	0x56, 0x22, 0xbe, 0x8a, 0xb1, 0xa1, 0xb0, 0x20, 0x12, 0xa6, 0xb6, 0xef, 0x93, 0xe4, 0x36, 0x0e,
	0xec, 0xce, 0xc4, 0x99, 0xbb, 0x52, 0xff, 0x80, 0x8f, 0xfe, 0x66, 0xd9, 0x99, 0xd9, 0x10, 0x45,
	0xec, 0xdb, 0x9c, 0x33, 0xe7, 0xde, 0x73, 0xbf, 0x20, 0x6b, 0xcc, 0x16, 0xeb, 0x72, 0x6f, 0x0d,
	0x19, 0x36, 0xf6, 0xe0, 0xec, 0x62, 0x67, 0xcc, 0xae, 0xc6, 0x4b, 0x4f, 0xae, 0xdb, 0xfb, 0x4b,
	0x52, 0x0d, 0x3a, 0x92, 0xcd, 0x3e, 0xe8, 0x66, 0x3f, 0x87, 0x70, 0xb2, 0x68, 0xe9, 0xab, 0x16,
	0xf8, 0xad, 0x45, 0x47, 0xec, 0x29, 0x24, 0xd5, 0x92, 0x0f, 0xf2, 0x41, 0x91, 0x8a, 0xa4, 0x5a,
	0x32, 0x0e, 0xd3, 0x3b, 0xb4, 0x4e, 0x19, 0xcd, 0x13, 0x4f, 0xf6, 0x90, 0xbd, 0x87, 0x93, 0xca,
	0xb9, 0x16, 0x2b, 0xed, 0x48, 0x6a, 0xe2, 0xc3, 0x7c, 0x50, 0x64, 0xf3, 0xb3, 0x32, 0x58, 0x96,
	0xbd, 0x65, 0xf9, 0xa5, 0xb7, 0x14, 0x7f, 0xe8, 0xd9, 0x4b, 0x98, 0x78, 0x6c, 0xf9, 0xc8, 0x27,
	0x8e, 0x88, 0xe5, 0x90, 0x2d, 0xd1, 0x91, 0xd2, 0x92, 0x3a, 0xd7, 0xb1, 0xff, 0x3c, 0xa6, 0xd8,
	0x07, 0x78, 0xb5, 0x70, 0x0e, 0x6d, 0x07, 0xae, 0x8c, 0x76, 0x6d, 0x83, 0xf6, 0x06, 0xed, 0x77,
	0xb5, 0xc1, 0x5b, 0xf1, 0x89, 0x4f, 0x7c, 0xc4, 0xff, 0x24, 0xac, 0x80, 0x67, 0xab, 0xae, 0xbe,
	0x8d, 0xa9, 0x3f, 0x2a, 0xbd, 0x55, 0x7a, 0xc7, 0xa7, 0x3e, 0xea, 0x6f, 0x9a, 0x5d, 0xc3, 0xf9,
	0x82, 0xc8, 0xaa, 0x75, 0x4b, 0x18, 0x12, 0x29, 0xbd, 0x8b, 0x99, 0x2a, 0xbd, 0xc5, 0x07, 0xfe,
	0xc4, 0x07, 0x3e, 0xa2, 0x62, 0xe7, 0x00, 0x02, 0x6b, 0xf9, 0xe3, 0x86, 0x24, 0x21, 0x4f, 0x7d,
	0xcc, 0x11, 0x33, 0xfb, 0x35, 0x80, 0xd1, 0xad, 0x43, 0xcb, 0x18, 0x8c, 0x3e, 0xcb, 0x06, 0xe3,
	0x0a, 0xfc, 0xbb, 0x1b, 0xd5, 0xb5, 0xb1, 0x8d, 0xa4, 0xb8, 0x83, 0x88, 0xba, 0xe5, 0x5c, 0x19,
	0x4d, 0xf8, 0x10, 0xa6, 0x9f, 0x8a, 0x1e, 0xfa, 0x35, 0xae, 0xe2, 0x60, 0x93, 0x6a, 0xc5, 0xde,
	0x00, 0x1c, 0x0a, 0x74, 0x7c, 0x9c, 0x0f, 0x8b, 0x6c, 0x7e, 0x5a, 0x86, 0x8b, 0x39, 0x7c, 0x88,
	0x23, 0xcd, 0xec, 0x1d, 0xa4, 0x07, 0xf4, 0xcf, 0xa2, 0x5e, 0xc0, 0xf8, 0x4e, 0xd6, 0x2d, 0xf2,
	0x24, 0x1f, 0x16, 0xa9, 0x08, 0x60, 0xb6, 0x86, 0xd3, 0x85, 0x25, 0x75, 0x2f, 0x37, 0x24, 0xd0,
	0xed, 0x8d, 0x76, 0xc8, 0x2e, 0x42, 0x6b, 0x3e, 0x3a, 0x9b, 0x67, 0xd1, 0xb6, 0xa3, 0x44, 0xe8,
	0xf9, 0x35, 0x4c, 0xe3, 0xfd, 0xf9, 0x06, 0xb3, 0xf9, 0xf3, 0xbe, 0xb4, 0xa3, 0xd3, 0x14, 0xbd,
	0x66, 0x3d, 0xf1, 0xb7, 0xf5, 0xf6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x26, 0x27, 0x3f,
	0xf2, 0x02, 0x00, 0x00,
}
