// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Allows storage of the request for cases where there
// is a user wait state such as entering a password
type AuthnRequest struct {
	ID                            string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version                       string               `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	IssueInstant                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=IssueInstant,proto3" json:"IssueInstant,omitempty"`
	Issuer                        string               `protobuf:"bytes,4,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Destination                   string               `protobuf:"bytes,5,opt,name=Destination,proto3" json:"Destination,omitempty"`
	AssertionConsumerServiceURL   string               `protobuf:"bytes,6,opt,name=AssertionConsumerServiceURL,proto3" json:"AssertionConsumerServiceURL,omitempty"`
	ProtocolBinding               string               `protobuf:"bytes,7,opt,name=ProtocolBinding,proto3" json:"ProtocolBinding,omitempty"`
	AssertionConsumerServiceIndex uint32               `protobuf:"varint,8,opt,name=AssertionConsumerServiceIndex,proto3" json:"AssertionConsumerServiceIndex,omitempty"`
	RelayState                    string               `protobuf:"bytes,9,opt,name=RelayState,proto3" json:"RelayState,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}             `json:"-"`
	XXX_unrecognized              []byte               `json:"-"`
	XXX_sizecache                 int32                `json:"-"`
}

func (m *AuthnRequest) Reset()         { *m = AuthnRequest{} }
func (m *AuthnRequest) String() string { return proto.CompactTextString(m) }
func (*AuthnRequest) ProtoMessage()    {}
func (*AuthnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *AuthnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthnRequest.Unmarshal(m, b)
}
func (m *AuthnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthnRequest.Marshal(b, m, deterministic)
}
func (m *AuthnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthnRequest.Merge(m, src)
}
func (m *AuthnRequest) XXX_Size() int {
	return xxx_messageInfo_AuthnRequest.Size(m)
}
func (m *AuthnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthnRequest proto.InternalMessageInfo

func (m *AuthnRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuthnRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AuthnRequest) GetIssueInstant() *timestamp.Timestamp {
	if m != nil {
		return m.IssueInstant
	}
	return nil
}

func (m *AuthnRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *AuthnRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *AuthnRequest) GetAssertionConsumerServiceURL() string {
	if m != nil {
		return m.AssertionConsumerServiceURL
	}
	return ""
}

func (m *AuthnRequest) GetProtocolBinding() string {
	if m != nil {
		return m.ProtocolBinding
	}
	return ""
}

func (m *AuthnRequest) GetAssertionConsumerServiceIndex() uint32 {
	if m != nil {
		return m.AssertionConsumerServiceIndex
	}
	return 0
}

func (m *AuthnRequest) GetRelayState() string {
	if m != nil {
		return m.RelayState
	}
	return ""
}

// Allows storage of user information to avoid
// repeated logins, basis of SSO
type User struct {
	Name                 string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Format               string       `protobuf:"bytes,2,opt,name=Format,proto3" json:"Format,omitempty"`
	Context              string       `protobuf:"bytes,3,opt,name=Context,proto3" json:"Context,omitempty"`
	IP                   string       `protobuf:"bytes,4,opt,name=IP,proto3" json:"IP,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,5,rep,name=Attributes,proto3" json:"Attributes,omitempty"`
	X509Certificate      []byte       `protobuf:"bytes,6,opt,name=X509Certificate,proto3" json:"X509Certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *User) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *User) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *User) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *User) GetX509Certificate() []byte {
	if m != nil {
		return m.X509Certificate
	}
	return nil
}

// User attributes
type Attribute struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// Allows storage of data required for artifact
// response until service provider retrieves it
type ArtifactResponse struct {
	User                 *User         `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Request              *AuthnRequest `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ArtifactResponse) Reset()         { *m = ArtifactResponse{} }
func (m *ArtifactResponse) String() string { return proto.CompactTextString(m) }
func (*ArtifactResponse) ProtoMessage()    {}
func (*ArtifactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *ArtifactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactResponse.Unmarshal(m, b)
}
func (m *ArtifactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactResponse.Marshal(b, m, deterministic)
}
func (m *ArtifactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactResponse.Merge(m, src)
}
func (m *ArtifactResponse) XXX_Size() int {
	return xxx_messageInfo_ArtifactResponse.Size(m)
}
func (m *ArtifactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactResponse proto.InternalMessageInfo

func (m *ArtifactResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ArtifactResponse) GetRequest() *AuthnRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthnRequest)(nil), "model.AuthnRequest")
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*Attribute)(nil), "model.Attribute")
	proto.RegisterType((*ArtifactResponse)(nil), "model.ArtifactResponse")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x2f, 0x3c, 0x0e, 0x50, 0x2d, 0x08, 0xad, 0x8a, 0xa0, 0x56, 0x4e, 0xbe, 0xe0,
	0x56, 0x41, 0x3d, 0x70, 0x41, 0x84, 0x44, 0x48, 0x96, 0x10, 0x8a, 0xb6, 0xb4, 0xe2, 0xba, 0x49,
	0xa6, 0xc1, 0x92, 0xbd, 0x1b, 0x76, 0xc7, 0xa8, 0xdc, 0xf9, 0x51, 0xfc, 0x3c, 0xb4, 0x6b, 0xbb,
	0x32, 0x15, 0xed, 0xcd, 0xef, 0xf9, 0xcd, 0xbc, 0xd9, 0x37, 0x03, 0x71, 0xa5, 0x77, 0x58, 0x66,
	0x07, 0xa3, 0x49, 0xb3, 0x91, 0x07, 0xc7, 0x27, 0x7b, 0xad, 0xf7, 0x25, 0x9e, 0x7a, 0x72, 0x53,
	0x5f, 0x9f, 0x52, 0x51, 0xa1, 0x25, 0x59, 0x1d, 0x1a, 0xdd, 0xec, 0xf7, 0x00, 0xa6, 0x8b, 0x9a,
	0xbe, 0x2b, 0x81, 0x3f, 0x6a, 0xb4, 0xc4, 0x9e, 0x40, 0x98, 0xaf, 0x78, 0x90, 0x04, 0x69, 0x24,
	0xc2, 0x7c, 0xc5, 0x38, 0x4c, 0xae, 0xd0, 0xd8, 0x42, 0x2b, 0x1e, 0x7a, 0xb2, 0x83, 0xec, 0x3d,
	0x4c, 0x73, 0x6b, 0x6b, 0xcc, 0x95, 0x25, 0xa9, 0x88, 0x0f, 0x92, 0x20, 0x8d, 0xe7, 0xc7, 0x59,
	0x63, 0x99, 0x75, 0x96, 0xd9, 0xd7, 0xce, 0x52, 0xfc, 0xa3, 0x67, 0x2f, 0x60, 0xec, 0xb1, 0xe1,
	0x43, 0xdf, 0xb8, 0x45, 0x2c, 0x81, 0x78, 0x85, 0x96, 0x0a, 0x25, 0xc9, 0xb9, 0x8e, 0xfc, 0xcf,
	0x3e, 0xc5, 0x3e, 0xc0, 0xcb, 0x85, 0xb5, 0x68, 0x1c, 0x58, 0x6a, 0x65, 0xeb, 0x0a, 0xcd, 0x05,
	0x9a, 0x9f, 0xc5, 0x16, 0x2f, 0xc5, 0x67, 0x3e, 0xf6, 0x15, 0x0f, 0x49, 0x58, 0x0a, 0x4f, 0xd7,
	0x6e, 0xbe, 0xad, 0x2e, 0x3f, 0x16, 0x6a, 0x57, 0xa8, 0x3d, 0x9f, 0xf8, 0xaa, 0xbb, 0x34, 0x5b,
	0xc1, 0xab, 0xfb, 0x1a, 0xe5, 0x6a, 0x87, 0x37, 0xfc, 0x51, 0x12, 0xa4, 0x8f, 0xc5, 0xc3, 0x22,
	0xf6, 0x1a, 0x40, 0x60, 0x29, 0x7f, 0x5d, 0x90, 0x24, 0xe4, 0x91, 0xb7, 0xea, 0x31, 0xb3, 0x3f,
	0x01, 0x0c, 0x2f, 0x2d, 0x1a, 0xc6, 0x60, 0xf8, 0x45, 0x56, 0xd8, 0x2e, 0xc0, 0x7f, 0xbb, 0xa0,
	0x3e, 0x69, 0x53, 0x49, 0x6a, 0x37, 0xd0, 0x22, 0xb7, 0x9a, 0xa5, 0x56, 0x84, 0x37, 0x4d, 0xf6,
	0x91, 0xe8, 0xa0, 0x5f, 0xe2, 0xba, 0x8d, 0x35, 0xcc, 0xd7, 0xec, 0x0c, 0x60, 0x41, 0x64, 0x8a,
	0x4d, 0x4d, 0x68, 0xf9, 0x28, 0x19, 0xa4, 0xf1, 0xfc, 0x28, 0x6b, 0xee, 0xe5, 0xf6, 0x87, 0xe8,
	0x69, 0x5c, 0x40, 0xdf, 0xce, 0xcf, 0xde, 0x2d, 0xdd, 0x9b, 0xae, 0x8b, 0xad, 0x9b, 0xda, 0xc5,
	0x3a, 0x15, 0x77, 0xe9, 0xd9, 0x39, 0x44, 0xb7, 0x75, 0xff, 0x1d, 0xff, 0x39, 0x8c, 0xae, 0x64,
	0x59, 0x23, 0x0f, 0x93, 0x41, 0x1a, 0x89, 0x06, 0xcc, 0x36, 0x70, 0xb4, 0x70, 0x4d, 0xe4, 0x96,
	0x04, 0xda, 0x83, 0x56, 0x16, 0xd9, 0x49, 0x13, 0x82, 0xaf, 0x8e, 0xe7, 0x71, 0x3b, 0xa0, 0xa3,
	0x44, 0x93, 0xce, 0x1b, 0x98, 0xb4, 0x77, 0xea, 0xa3, 0x88, 0xe7, 0xcf, 0xba, 0x47, 0xf4, 0x4e,
	0x58, 0x74, 0x9a, 0xcd, 0xd8, 0xdf, 0xe0, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x90,
	0x64, 0xb4, 0x1a, 0x03, 0x00, 0x00,
}
